### ISSUE TITLE
Scroll Down support

### ISSUE THREAD

**Issue by soufiane-fadil** [mrharel/scrappy#1]
Dear all,

How can i scroll down the document , i have a website with infinite scroll, how can i do it ?

Many thanks

**Comment by mrharel** [comment]
Unfortunately scrappy doesn't support that since the focus is on the scrapping and not the grabbing the content. 

What you can do is to use a headless browser like phantomjs, grab the html after how many scrolls you need and then pass the html to scrappy.

**Comment by soufiane-fadil** [comment]
Thanks 👍
