### ISSUE TITLE
How to run your exemple

### ISSUE THREAD

**Issue by ghost** [mrharel/scrappy#2]
Hi dude,

thanks for your scrapper it really looks powerfull.

I can not figure out to launch your exemple express-server.js

Do I have to do "node express-server.js" ?
Because I've    Error: Cannot find module 'scrappy'

Thanks for your answer

**Comment by mrharel** [comment]
it seems that the module was not installed. did you do `npm install @mrharel/scrappy` ?

[Edit] i think there is also a bug there, and the correct way to require it is:
```
var scrappy = require('@mrharel/scrappy');
```

**Comment by ghost** [comment]
I've many errors on my npm install :

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@mrharel/scrappy" "--save"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install @mrharel/scrappy as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\leona\Desktop\scrappy-master\examples\npm-debug.log

**Comment by mrharel** [comment]
that is strange, for some reason it tries to install itself as a dependency.

i suggest starting from scratch again just to make sure we start from a clean setup:
1. do git clone
1. then npm install
1. and then change the code in the example file to the correct module name as i mentioned above

let me know if this works

**Comment by mrharel** [comment]
i am assuming this was resolved
